version: '3'
services:
  hacktoday:
    container_name: beri-aku 
    restart: always
    build:
      context: .
      args:
              binary: server.py
    ports:
      - "15001:5000" # exposed:local
    read_only: true
